KebeleDataManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('kebele/', include('kebele.urls')),
    
    
    
        # password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"), 
    
    #email sent message
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),  
    
    #email with link and instructions
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),  
    
    #password reset success
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),  
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kebele/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    
    # resident management
    path('mr/', views.manage_resident, name="manage-resident"),
    path('add-resident/', views.add_resident, name="add-resident"),
    path('update-resident/<str:id>/', views.update_resident, name="update-resident"),
    path('view-resident/<str:id>/', views.view_resident, name="view-resident"),
         #address
    path('add-address/<str:id>/', views.add_address, name="add-address"),
    path('update-address/<str:id>/', views.update_address, name="update-address"),
         #house
    path('add-house/', views.add_house, name="add-house"),
    path('update-house/<str:id>/', views.update_house, name="update-house"),
    path('view-house/<str:id>/', views.view_house, name="view-house"),
         #family
    path('add-family/', views.add_family, name="add-family"),
    path('update-family/<str:id>/', views.update_family, name="update-family"),
    path('view-family/<str:id>/', views.view_family, name="view-family"),
         #id card
    path('add-idcard/', views.add_id_card, name="add-idcard"),
    path('update-idcard/<str:id>/', views.update_id_card, name="update-idcard"),
    path('view-idcard/<str:id>/', views.view_idcard, name="view-idcard"),
    
     # ? end of resident management
    
    
#     path('mvd', views.manage_vital_data, name="manage-vital-data"),
    
    #local business management
    path('mlb', views.manage_local_business, name="manage-local-business"),
    
    #local business
    path('add-local-business/', views.add_local_business, name="add-local-business"),
    path('update-local-business/<str:id>/', views.update_local_business, name="update-local-business"),
    path('delete-local-business/<str:id>/', views.delete_local_business, name="delete-local-business"),
    
    #local business owners
    path('add-lb-owner/', views.add_lb_owner, name="add-lb-owner"),
    path('update-lb-owner/<str:id>/', views.update_lb_owner, name="update-lb-owner"),
    path('delete-lb-owner/<str:id>/', views.delete_lb_owner, name="delete-lb-owner"),
        
    # managing kebele house
    path('mkh', views.manage_kebele_house, name="manage-kebele-house"),
    path('add-kebele-house/', views.add_kebele_house, name="add-kebele-house"),
    path('update-kebele-house/<str:id>/', views.update_kebele_house, name="update-kebele-house"),
    path('view-kh/<str:id>/', views.view_kebele_house, name="view-kh"),
    
    
    
        # certificates
    path('certificate', views.certificates, name="certificates"),
    path('add-certificate/', views.add_birth_certificate, name="add-birth-certificate"),
    path('update-bc/<str:id>/', views.update_birth_certificate, name="update-bc"),
    path('view-bc/<str:id>/', views.view_birth_certificate, name="view-bc"),
    
        

#see map
path('map/',views.see_map,name="see-map"),
path('map/<str:pk>/',views.see_house_in_map,name="see-house-in-map"),
    
]

kebele/models.py
from django.db import models

# Create your models here.
from django.contrib.gis.db import models
from django.db.models.signals import post_save, post_delete


class Kebele(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    woreda = models.CharField(max_length=200, null=True, blank=True)
    zone = models.CharField(max_length=200, null=True, blank=True)
    region = models.CharField(max_length=200, null=True, blank=True)
    
    def __str__(self):
        return self.name
    

class Resident(models.Model):
    SAALA=(
        ('Male', 'Male'),
        ('Female', 'Female'),    
    )
    
    EDUCATION_LEVEL=(
        ('elementary', 'Elementary'),
        ('hight_school', 'High School'),    
        ('diploma', 'Diploma'),    
        ('degree', 'Degree'),    
        ('masters', 'Masters'),    
        ('phd', 'PHD'),    
    )
    
    OCCUPATION=(
        ('teacher', 'Teacher'),
        ('merchant', 'Merchant'),    
        ('office_worker', 'Office Worker'),    
        ('nurse', 'Nurse'),    
        ('doctor', 'Doctor'),    
        ('student', 'Student'),   
        ('other', 'Other'),  
        ('none', 'None'),   
    )
    resident_id = models.CharField(max_length=100, null=True, blank=True)
    kebele = models.ForeignKey(Kebele, on_delete=models.SET_NULL, null=True, blank=True )
    first_name=models.CharField(max_length=100, null=True, blank=True)
    middle_name=models.CharField(max_length=100, null=True, blank=True)
    last_name=models.CharField(max_length=100, null=True, blank=True)
    mother_name=models.CharField(max_length=100, null=True, blank=True)
    photo=models.ImageField(null=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    age = models.IntegerField(null=True)
    sex = models.CharField(max_length=20, null=True, blank=True, choices=SAALA)
    edu_level = models.CharField(max_length=200, null=True, blank=True, choices=EDUCATION_LEVEL)
    nationality = models.CharField(max_length=100, null=True, blank=True, default="Ethiopian")
    religion = models.CharField(max_length=100, null=True, blank=True)
    occupation = models.CharField(max_length=100, null=True, blank=True, choices=OCCUPATION)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str((self.resident_id ))
    class Meta:
        ordering = ['first_name']
    
    
class Address(models.Model):
    resident = models.OneToOneField(Resident, on_delete=models.CASCADE, null=True, blank=True)
    hnum = models.ForeignKey('House', on_delete=models.SET_NULL, null=True, blank=True)
    zone = models.CharField(max_length=100, null=True, blank=True)
    gooxii = models.CharField(max_length=100, null=True, blank=True)
    garee = models.CharField(max_length=100, null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.resident)
    class Meta:
        ordering = ['resident']
        
        
class IDCard(models.Model):
    resident = models.OneToOneField(Resident, on_delete=models.CASCADE, null=True, blank=True)
    emergency = models.CharField(max_length=200, null=True, blank=True)
    emergency_contact= models.IntegerField(null=True, blank=True)
    # id_number = models.CharField(max_length=20, null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.resident)
        

class House(models.Model):
    owner = models.ForeignKey(Resident, on_delete=models.CASCADE, null=True, blank=True)
    hnum = models.CharField(max_length=100, null=True, blank=True)
    door_number= models.IntegerField(null=True, blank=True)
    area = models.CharField(max_length=100, null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.hnum)
    
        
class Family(models.Model):
    leader = models.ForeignKey(Resident, on_delete=models.CASCADE, null=True, blank=True)
    members = models.ManyToManyField(Resident, related_name="family_members")
    family_number= models.IntegerField(null=True, blank=True)
    male_number= models.IntegerField(null=True, blank=True)
    female_number= models.IntegerField(null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.leader)
    
    
    
    
    
   ################################################### 
   
class BusinessOwner(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.name)
    
   
class LocalBusiness(models.Model):
    owner = models.ForeignKey(BusinessOwner, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    type= models.CharField(max_length=100, null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.owner.name)
    

 

    
    
class KebeleHouse(models.Model):
    hnum = models.CharField(max_length=100, null=True, blank=True)
    door_number= models.IntegerField(null=True, blank=True)
    area = models.CharField(max_length=100, null=True, blank=True)
    resident = models.OneToOneField(Resident,on_delete=models.SET_NULL,null=True,blank=True)
    location = models.PointField(null=True, blank=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.hnum)
    

    @property   
    def lat_lng(self): 
      return list(getattr(self.location,'coords',[])[::-1])
                
                
                
class BirthCertificate(models.Model):
    SAALA=(
        ('Male', 'Male'),
        ('Female', 'Female'),    
    )
    child = models.CharField(max_length=100, null=True, blank=True)
    birth_registration_number = models.BigIntegerField(null=True, blank=True)
    birth_unique_number = models.BigIntegerField(null=True, blank=True)
    father = models.ForeignKey(Resident, on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'sex': 'Male'})
    mother = models.ForeignKey(Resident, on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'sex': 'Female'}, related_name="mothers")
    sex = models.CharField(max_length=20, null=True, blank=True, choices=SAALA)
    birthday = models.DateField(null=True, blank=True)
    birth_place = models.CharField(max_length=100, null=True, blank=True)
    nationality = models.CharField(max_length=100, null=True, blank=True, default="Ethiopian")
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.child)
    
    
    
    
def add_resident_id(sender, instance, created, **kwargs):
    resident = instance
    if created == True:
        resident.resident_id  =  "G/H/M/J " + str(resident.id)
        resident.save()
        

post_save.connect(add_resident_id, sender=Resident)

kebele/forms.py
from django.forms import ModelForm, widgets
from django import forms
from .models import Resident, LocalBusiness, Address, House, Family, IDCard, BirthCertificate, KebeleHouse,  BusinessOwner

class ResidentForm(ModelForm):
    class Meta:
        model= Resident
        exclude=['kebele','resident_id']
        
        
    def __init__(self, *args, **kwargs):
        super(ResidentForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
               

class AddressForm(ModelForm):
    class Meta:
        model= Address
        exclude = ['resident'] 
        
        labels = {
            'hnum': 'Lives in ',
            'gooxii': 'Local community',
            'garee': 'Group',

        }
        
    def __init__(self, *args, **kwargs):
        super(AddressForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            
            
        
class HouseForm(ModelForm):
    class Meta:
        model= House
        fields = '__all__'
        
        labels = {
            'hnum': 'House number ',
        }
        
    def __init__(self, *args, **kwargs):
        super(HouseForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        
        
class FamilyForm(ModelForm):
    class Meta:
        model= Family
        fields = '__all__'


        widgets = {
            'members': forms.CheckboxSelectMultiple(),
        }
        
    def __init__(self, *args, **kwargs):
        super(FamilyForm, self).__init__(*args, **kwargs)
        self.fields['leader'].widget.attrs.update({'class': 'form-control'})
        self.fields['members'].widget.attrs.update({'id': 'form-check-input'})
        self.fields['family_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['male_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['female_number'].widget.attrs.update({'class': 'form-control'})
        
        
class IDCardForm(ModelForm):
    class Meta:
        model= IDCard
        fields = '__all__'
        

        
    def __init__(self, *args, **kwargs):
        super(IDCardForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})


class BusinessOwnerForm(ModelForm):
    class Meta:
        model = BusinessOwner
        fields = '__all__'
        

        
    def __init__(self, *args, **kwargs):
        super(BusinessOwnerForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        
class LocalBusinessForm(ModelForm):
    class Meta:
        model= LocalBusiness
        fields = '__all__'
        

        
    def __init__(self, *args, **kwargs):
        super(LocalBusinessForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        
class KebeleHouseForm(ModelForm):
    class Meta:
        model= KebeleHouse
        fields = '__all__'
        
        labels = {
            'hnum': 'House number',

        }
        
    def __init__(self, *args, **kwargs):
        super(KebeleHouseForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        
        
        
class BirthCertificateForm(ModelForm):
    class Meta:
        model= BirthCertificate
        fields = '__all__'

        
    def __init__(self, *args, **kwargs):
        super(BirthCertificateForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
        

kebele/templates/kebele/add_kebele_house.html
<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
        integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />


    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
        integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
</head>

{% extends 'main.html' %}
{% load static %}

{% block content %}



    <div class="container">
      

        <form action="" method="POST" class="form-control">
            {% csrf_token %}
            <div class="row">

                <div class="col-lg-5">
                    <label>House Number</label>
                    <br>
                    <input type="text" name="hnum" required class="form-control" id="id_hnum">
    
                    <br>
                    <label>Door Number</label>
                    <br>
                    <input type="number" min="1" name="door_number" class="form-control" id="id_door_number" required>
                    <br>
                    <label> Area in square meter</label><br>
                    <input type="text" name="area" class="form-control" id="id_area" required>
                    <br>
                    <label for="cars">Who is Living in</label>
                    <br>
                    <select name="resident" id="resident" class="form-control">
                        <option value="">Leave it open</option>
                        {% for resident in residents %}
                        <option value="{{resident.id}}">{{ resident.resident_id }}  {{ resident.middle_name }}</option>
                        {% endfor %}
    
                    </select>
                    <input type="hidden" name="lat" id="lat" required>
                    <input type="hidden" name="lng" id="lng" required>
                    <input style="display:none;" type="text" id="checking" required>
    
                </div>
                <div class="col-lg-7">
                    <div class="">
                        <h6 class=" displayer none-header">Select the house's location in the map </h2>
                    </div>
    
                    <div style="height:350px; width:100%" id="map"></div>
    
                </div>
            </div>







<div class=" d-flex justify-content-center mt-3">
<div>

    <input type="submit" value="Save" class="btn btn-primary btn-lg">
</div>
</div>

        </form>

    </div>


<br>
<br>






<script type="text/javascript">
    window.onload = () => {
        search();
    };

    function search() {

        var map = L.map('map').setView([7.66749, 36.83229], 16.4);

        L.tileLayer('http://{s}.google.com/vt/lyrs=s,p&x={x}&y={y}&z={z}', {
            maxZoom: 20,
            subdomains: ['mt0', 'mt1', 'mt2', 'mt3'],
            attribution: '&copy; <a href="https://yai-devs.netlify.app/" target = "_blank">From Yai</a>'
        }).addTo(map);


        var kebele = [{
            "type": "Feature",
            "properties": {
                "Name": "Mantina Kebele"
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [36.832250, 7.666792],
                        [36.832083, 7.666781],
                        [36.831907, 7.666767],
                        [36.831792, 7.666760],
                        [36.831650, 7.666750],
                        [36.831510, 7.666750],
                        [36.831347, 7.666767],
                        [36.831142, 7.666783],
                        [36.831142, 7.666893],
                        [36.831050, 7.666917],
                        [36.830917, 7.666942],
                        [36.830817, 7.666958],
                        [36.830733, 7.666975],
                        [36.830617, 7.666992],
                        [36.830617, 7.667150],
                        [36.830633, 7.667317],
                        [36.830633, 7.667467],
                        [36.830617, 7.667525],
                        [36.830517, 7.667575],
                        [36.830333, 7.667625],
                        [36.830250, 7.667667],
                        [36.830233, 7.667750],
                        [36.830333, 7.667950],
                        [36.830550, 7.668150],
                        [36.830817, 7.668367],
                        [36.831100, 7.668600],
                        [36.831392, 7.668817],
                        [36.831683, 7.669058],
                        [36.831933, 7.669258],
                        [36.832083, 7.669350],
                        [36.832083, 7.669317],
                        [36.832092, 7.669200],
                        [36.832083, 7.669058],
                        [36.832058, 7.668850],
                        [36.832042, 7.668617],
                        [36.832025, 7.668375],
                        [36.832025, 7.668217],
                        [36.832010, 7.668058],
                        [36.831990, 7.667975],
                        [36.831968, 7.667833],
                        [36.831958, 7.667725],
                        [36.831933, 7.667600],
                        [36.831917, 7.667517],
                        [36.831917, 7.667417]
                    ]
                ]
            }
        }];


        L.geoJSON(kebele, {
            style: function (feature) {
                switch (feature.properties.Name) {
                    case 'Mantina Kebele':
                        return {
                            color: "#0000ff", opacity: 0.97
                        };
                }
            }
        }).addTo(map);
        var popup = L.popup();




        function onMapClick(e) {
            popup
                .setLatLng(e.latlng)
                .setContent("selected point for kebele house")
                .openOn(map);
            document.getElementById("checking").value = "done";
            document.getElementById('lat').value = e.latlng.lat;
            document.getElementById('lng').value = e.latlng.lng;



        }

        map.on('click', onMapClick);
    }
</script>


<script src="{% static 'vendors/house_validation.js' %}"></script>
{% endblock content %}

kebele/templates/kebele/birth_form.html
{% extends 'main.html' %}

{% load static %}
{% block content%}



  <div class="container">


<form action="" method="POST" name="myform" enctype="multipart/form-data">
 {% csrf_token %}
     
 <div>
  <label for="">Child name</label>
  {{form.child}}
</div>


<div>
  <label for="">Birth registration number</label>
  {{form.birth_registration_number}}
</div>

<div>
  <label for="">Birth unique number</label>
  {{form.birth_unique_number}}
</div>


 {% if certificate.father %}

 <div>
  <label for="father">Father</label>

  <input required type="text" name="father" list="father-list" class="form-control" value="{{certificate.father}}">
  <datalist id="father-list">
    <select name="father" id="id_resident">
    {{form.father}}
  </datalist>
</div>

{% else %}

<div>
  <label for="father">Father</label>
  <input required type="text" name="father" list="father-list" class="form-control" >
  <datalist id="father-list">
    <select name="father" id="id_resident">
    {{form.father}}
  </datalist>
</div>

{% endif %}


{% if certificate.mother  %}

<div>
 <label for="mother">Mother</label>

 <input required type="text" name="mother" list="mother-list" class="form-control" value="{{certificate.mother}}">
 <datalist id="mother-list">
   <select name="mother" id="id_resident">
   {{form.mother}}
 </datalist>
</div>


{% else %}

<div>
  <label for="mother">Mother</label>
 
  <input required type="text" name="mother" list="mother-list" class="form-control" >
  <datalist id="mother-list">
    <select name="mother" id="id_resident">
    {{form.mother}}
  </datalist>
 </div>

{% endif %}


<div>
  <label for="">Sex</label>
  {{form.sex}}
</div>

<div>
  <label for="">Birthday</label>
  {{form.birthday}}
</div>


<div>
  <label for="">Birth place</label>
  {{form.birth_place}}
</div>

<div>
  <label for="">Nationality</label>
  {{form.nationality}}
</div>

 <input type="submit" value="Save" class="btn btn-primary">
</form>


</div>

<br>
<br>


<script src="{% static 'vendors/certificate.js' %}"></script>
{% endblock content%}

kebele/templates/kebele/delete.html
{% extends 'main.html' %}

{% block content %}


    <div class="container">
<h2> "{{object}}" balleessuu barbaadduu?</h2>
<form action="" method="POST">
    {% csrf_token %}

    <a href="{% url 'home'%}"> Haqi</a> | 
    <input type="submit" value="Balleessi">
</form>

</div>

{% endblock content %}

kebele/templates/kebele/lb_form.html
{% extends 'main.html' %}
{% load static %}
{% block content%}


  <div class="container">
 

<form action="" method="POST" name="myform" enctype="multipart/form-data">
 {% csrf_token %}

 {% if local_business.owner %}

   <div>
    <label for="">Owner</label>

    <input required type="text" name="owner" list="resident-list" class="form-control" value="{{local_business.owner}}">
    <datalist id="resident-list">
      <select name="owner" id="id_resident">
      {{form.owner}}
    </datalist>
  </div>

  {% else %}
 
  <div>
    <label for="">Owner</label>

    <input required type="text" name="owner" list="resident-list" class="form-control">
    <datalist id="resident-list">
      <select name="owner" id="id_resident">
      {{form.owner}}
    </datalist>
  </div>

  {% endif %}

  <div>
    <label for="">Business name</label>
    {{form.name}}
  </div>

 
  <div>
    <label for="">Type</label>
    {{form.type}}
  </div>
   

 <input type="submit" value="Save" class="btn btn-primary">
</form>

</div>


<br>
<br>

<script src="{% static 'vendors/local_bmgt.js' %}"></script>

{% endblock content%}

kebele/templates/kebele/lb_owner_form.html
{% extends 'main.html' %}
{% load static %}

{% block content%}


  <div class="container">


<form action="" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
    
   {{form.as_p}}

 <input type="submit" value="Save" class="btn btn-primary">
</form>

</div>


<br>
<br>



<script src="{% static 'vendors/local_bmgt.js' %}"></script>
{% endblock content%}

kebele/templates/kebele/manage_kebele_house.html
{% extends 'main.html' %}

{% block content %}


    <div class="container">
    <div id="example_wrapper" class="dataTables_wrapper dt-bootstrap5">
        <h3>Kebele Houses</h3>
        <a href="{% url 'see-map' %}"><button class="btn btn-outline-info">View on map</button></a> <br>

        
        <div class="d-flex justify-content-end mb-2">
            <div>
                <a href="{% url 'add-kebele-house' %}"><button class="btn btn-outline-info">   Add kebele house</button> </a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 table-responsive">
                <table id="housetable" class="table dataTable table-bordered table-striped" style="width: 100%"
                    aria-describedby="example_info">
                    <thead>
                        <tr>
                            <th class="sorting sorting_asc" tabindex="0" aria-controls="example" rowspan="1"
                                colspan="1" style="width: 61.5833px" aria-sort="ascending"
                                aria-label="Name: activate to sort column descending">
                                House number
                            </th>

                            <th class="sorting sorting_asc" tabindex="0" aria-controls="example" rowspan="1"
                            colspan="1" style="width: 61.5833px" aria-sort="ascending"
                            aria-label="Name: activate to sort column descending">
                            Lives in
                        </th>

                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"
                                style="width: 82.8px" aria-label="Position: activate to sort column ascending">
                                Door
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"
                                style="width: 56.6833px" aria-label="Office: activate to sort column ascending">
                                Area
                            </th>

                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"
                                style="width: 30.2167px" aria-label="Age: activate to sort column ascending">
                                Registered at
                            </th>

                            <th rowspan="1" colspan="1" style="width: 62px">Actions</th>
                        </tr>
                    </thead> 
                    <tbody>
                        {% for kebele_house in kebele_houses %}
                        <tr class="odd">
                            <td>{{kebele_house.hnum}}</td>
                            <td>{{kebele_house.resident.first_name}} {{kebele_house.resident.last_name}}</td>
                            <td>{{kebele_house.door_number}}</td>
                            <td>{{kebele_house.area}}</td>
                            <td>{{kebele_house.created}}</td>

                            <td class="update-table">
                                <a href="{% url 'update-kebele-house' kebele_house.id %}"><button
                                        class="btn btn-sm btn-danger">Edit</button></a>
                                <a href="{% url 'see-house-in-map' kebele_house.id %}"><button class="btn btn-sm btn-info">View Map</button></a>
                            </td>
                        </tr>
                        {%endfor%}

                    </tbody>
                    <tfoot>
                        <tr>
                            <th rowspan="1" colspan="1">House number</th>
                            <th rowspan="1" colspan="1">Lives in</th>
                            <th rowspan="1" colspan="1">Door</th>
                            <th rowspan="1" colspan="1">Area</th>
                            <th rowspan="1" colspan="1">Registered at</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

      
    </div>


</div>


{% endblock content%}

kebele/templates/kebele/manage_vital_data.html
{% extends 'main.html' %}

{% block content %}
<div class="home-content">

manage vital data
</div>

{% endblock content%}

kebele/templates/kebele/view_house.html
{% extends 'main.html' %}

{% block content %}


    <div class="container">
        <div class="show-detail d-flex flex-column align-items-center bg-white">
            <div class="detail-photo">

            </div>
            <div class="detail info">
                <div>Owner: <a href="{% url 'view-resident' house.owner.id %}">{{house.owner.first_name}} {{house.owner.middle_name}} {{house.owner.last_name}} </a></div>
                <div>House number: {{house.hnum}}</div>
                <div>Door number: {{house.door_number}}</div>
                <div>Area: {{house.area}}</div>



            </div>
        </div>
    </div>



{% endblock content %}